apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: public.ecr.aws/b1m7t7i1/jupyter-granica-demo:v1
          resources:
            requests:
              memory: 1G
            limits:
              memory: 1G
          env:
            - name: JUPYTER_PORT
              value: "8888"
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef: 
                  name: aws-secrets
                  key: aws-secret-key
            - name: AWS_ACCESS_KEY_ID
              valueFrom: 
                secretKeyRef:
                  name: aws-secrets
                  key: aws-access-key  
          ports:
            - name: http 
              containerPort: 8888
              protocol: TCP
            - name: web-ui
              containerPort: 4040
              protocol: TCP
      serviceAccount: spark
      serviceAccountName: spark
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter
spec:
  type: ClusterIP
  selector:
    app: jupyter
  ports:
    - port: 8888
      protocol: TCP
      targetPort: http
      name: http
    - port: 4040
      protocol: TCP
      targetPort: web-ui
      name: web-ui

---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-headless
spec:
  clusterIP: None
  selector:
    app: jupyter